version: 2
 jobs:
   build:
        working_directory: ~/labord-react
     environment:
            - AWS_S3_BUCKET_NAME: labord-s3
     docker:
       - image: cdssnc/aws-cli
     steps:
       - checkout
       - run:
           name: Deploy to S3
           command: |
               aws s3 sync ~/labord-react s3://${AWS_S3_BUCKET_NAME}/ --exact-timestamps --delete
