version: 2 # 未完成
 jobs:
   build:
        working_directory: ~/repo
     environment:
            - AWS_S3_BUCKET_NAME: YOUR_BUCKET_NAME
     docker:
       - image: cdssnc/aws-cli
     steps:
       - checkout
       - run:
           name: Deploy to S3
           command: |
               aws s3 sync ~/repo s3://${AWS_S3_BUCKET_NAME}/ --exact-timestamps --delete
